spring:
  application:
    name: boutique
  
# --- Configuration de la base de donn√©es (MySQL Inactive) ---
#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mama}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#    username: ${DB_USER:root}
#    password: ${DB_PASSWORD:}
#    driver-class-name: com.mysql.cj.jdbc.Driver

  # --- Configuration JPA pour MySQL (Inactive) ---
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    database-platform: org.hibernate.dialect.MySQLDialect

# --- Configuration pour PostgreSQL (Active) ---
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

#