spring:
  application:
    name: boutique
  
  # --- Configuration de la base de donn√©es (MySQL Active) ---
  datasource:
    url: jdbc:mysql://localhost:3306/rpx?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: ${DB_USER:your_db_user}
    password: ${DB_PASSWORD:your_db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  # --- Configuration JPA ---
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# --- Configuration pour PostgreSQL (Inactive) ---
#  datasource:
#    url: jdbc:postgresql://localhost:5432/boutiquedb
#    username: postgres
#    password: ''
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085