spring:
  application:
    name: boutique
  
  # --- Configuration de la base de données (MySQL Active) ---
  datasource:
    url: jdbc:mysql://localhost/:3306/rpx?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  # --- Configuration JPA ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# --- Configuration pour PostgreSQL (Inactive) ---
#  datasource:
#    url: jdbc:postgresql://localhost:5432/boutiquedb
#    username: postgres
#    password: ''
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085
  servlet:
    session:
      timeout: 10m # Déconnexion automatique après 10 minutes d'inactivité